name: 'Setup Node.js and Install Dependencies'
description: 'Sets up Node.js, caches dependencies, runs npm ci, and optionally installs Playwright.'

inputs:
  install-playwright:
    description: 'Whether to install Playwright browsers'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION || '20.13.0' }}

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true'
      run: npx playwright install --with-deps
      shell: bash
