name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 20.13.0
  VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  VITE_SENTRY_ORG: ${{ vars.VITE_SENTRY_ORG }}
  VITE_SENTRY_PROJECT: ${{ vars.VITE_SENTRY_PROJECT }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
      - name: Run ESLint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
      - name: Check TypeScript types
        run: npm run typecheck

  unit-tests:
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Run Unit Tests
        run: npm run test

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-results/

  component-tests:
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
        with:
          install-playwright: 'true'

      - name: Run Component Tests
        run: npm run test:playwright:component

      - name: Upload component test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: component-test-report
          path: |
            playwright-report/
            test-results/

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
        with:
          install-playwright: 'true'

      - name: Run E2E Tests
        run: npm run test:playwright:e2e

      - name: Upload Playwright Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: |
            playwright-report/
            test-results/

  build:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, unit-tests, component-tests, e2e-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Build frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./dist
